create table line (
   COMP_CD NUMBER(20),
   PLANT_CD NUMBER(20),
  LINE_CD VARCHAR2(50),
   LINE_NM VARCHAR2(50) not null,
   USE_YN char(1) not null,
   REMARK VARCHAR2(50),
   IN_USR_ID VARCHAR2(50),
   IN_DATE DATE not null,
   UP_USR_ID VARCHAR2(50),
   UP_DATE DATE,
   CONSTRAINT TEST_2 PRIMARY KEY(COMP_CD, PLANT_CD, LINE_CD)
   );